services:
        site:
                image: murillok/docker-images:site_rg-v1.0
                ports:
                        - "8080:8080"
                networks:
                        - rede-compose
                depends_on:
                        - db
        db:
                image: murillok/docker-images:db_rg-v1.0
                ports:
                        - "3306:3306"
                networks:
                        - rede-compose
networks:
        rede-compose:
                driver: bridge
                